In [ ]:
import ajtest
import cvxpy as cvx
import numpy as np

np.random.seed(0)
m,n = 4,8
A = np.random.rand(m,n)
b = np.random.rand(m)
gamma = .1
print b

In [2]:
x = cvx.Variable(n)
prob = cvx.Problem(cvx.Minimize(cvx.norm(A*x-b) + gamma*cvx.norm(x,1)))
prob.solve(verbose=True,solver='SCS')

----------------------------------------------------------------------------
	SCS v1.1.0 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
----------------------------------------------------------------------------
Lin-sys: sparse-direct, nnz in A = 65
eps = 1.00e-03, alpha = 1.50, max_iters = 2500, normalize = 1, scale = 1.00
Variables n = 17, constraints m = 21
Cones:	linear vars: 16
	soc vars: 5, soc blks: 1
Setup time: 6.98e-04s
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
     0|      inf       inf       nan      -inf       inf       inf  6.49e-04 
   100| 4.69e-03  1.22e-02  4.85e-04  2.31e-01  2.31e-01  5.97e-17  8.32e-04 
   200| 2.73e-03  3.01e-03  9.08e-06  2.31e-01  2.31e-01  6.00e-17  1.07e-03 
   300| 7.32e-04  1.86e-03  1.25e-06  2.31e-01  2.31e-01  5.99e-17  1.5

0.23102226979269191

In [3]:
x.value

matrix([[  8.87954067e-01],
        [  1.28566190e-05],
        [ -7.42899668e-01],
        [  5.48272946e-01],
        [ -1.19370389e-04],
        [ -5.61516591e-05],
        [  5.25885540e-05],
        [  1.31183443e-01]])

In [4]:
data = prob.get_problem_data('SCS')
result = ajtest.myscs(data, data['dims'], alpha=1.5, scale=1)

----------------------------------------------------------------------------
	SCS v1.1.0 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
----------------------------------------------------------------------------
Lin-sys: sparse-direct, nnz in A = 65
eps = 1.00e-03, alpha = 1.50, max_iters = 2500, normalize = 1, scale = 1.00
Variables n = 17, constraints m = 21
Cones:	linear vars: 16
	soc vars: 5, soc blks: 1
Setup time: 1.65e-03s
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
     0|      nan       nan       nan       nan       nan       nan  1.87e-03 
   100|      nan       nan       nan       nan       nan       nan  2.23e-03 
   200|      nan       nan       nan       nan       nan       nan  2.59e-03 
   300|      nan       nan       nan       nan       nan       nan  2.9

In [5]:
result['x']

array([  8.87954067e-01,   1.28566190e-05,  -7.42899668e-01,
         5.48272946e-01,  -1.19370389e-04,  -5.61516591e-05,
         5.25885540e-05,   1.31183443e-01,  -3.35134635e-06,
         8.87914739e-01,  -1.24285114e-07,   7.42883097e-01,
         5.48382203e-01,  -1.24285114e-07,  -1.24285114e-07,
        -1.24285114e-07,   1.31076671e-01])

In [6]:
prob.unpack_results('SCS', result)

In [7]:
x.value

matrix([[  8.87954067e-01],
        [  1.28566190e-05],
        [ -7.42899668e-01],
        [  5.48272946e-01],
        [ -1.19370389e-04],
        [ -5.61516591e-05],
        [  5.25885540e-05],
        [  1.31183443e-01]])

In [5]:
data

{'A': <21x17 sparse matrix of type '<type 'numpy.float64'>'
 	with 65 stored elements in Compressed Sparse Column format>,
 'F': <function cvxpy.problems.problem_data.matrix_data.F>,
 'G': <0x17 sparse matrix of type '<type 'numpy.float64'>'
 	with 0 stored elements in Compressed Sparse Column format>,
 'b': array([-0.        , -0.        , -0.        , -0.        , -0.        ,
        -0.        , -0.        , -0.        , -0.        , -0.        ,
        -0.        , -0.        , -0.        , -0.        , -0.        ,
        -0.        , -0.        , -0.45615033, -0.56843395, -0.0187898 ,
        -0.6176355 ]),
 'bool_vars_idx': [],
 'c': array([ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0.1,  0.1,
         0.1,  0.1,  0.1,  0.1,  0.1,  0.1]),
 'dims': {'ep': 0, 'f': 0, 'l': 16, 'q': [5], 's': []},
 'h': array([], dtype=float64),
 'int_vars_idx': [],
 'offset': 0.0}